# tasks file for sonarqube

#- name: Copying the sonarqube zip
#  copy:
#        src: sonarqube-7.8.zip
#        dest: /opt

#- name: unzipping sonarqube
#  unarchive:
#        src: /opt/sonarqube-7.8.zip
#        dest: /opt

- name: Downloading Sonarqube 7.8
  command: wget -P /opt/ https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.8.zip

#- name: Installing Unzip in Ubuntu
#  apt:
#        name: unzip
#        state: present
#  when: ansible_os_family == "Debian"

- name: unzipping
  command: sudo runuser -l root -c 'tar -C  /opt/ -xvf /opt/sonarqube-7.8.zip'


- name: Add the user 'sonar' for security reasons
  user:
        name: sonar
        shell: /bin/bash

#- name: Giving sudo previleges
#  copy:
#        src: sudoers
#        dest: /etc/sudoers

- name: Givin sudo privileges to sonar user
  command: echo "ansible ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/ansible

- name: Changing the permissions owner and group of the sonarqube
  file:
        path: /opt/sonarqube-7.8
        state: directory
        mode: '0755'
        owner: sonar
        group: sonar
        

